dist: xenial
language: cpp
compiler: 
- gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
install:
- pip install conan
- conan user
- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
script:
- export CC=gcc-7
- export CXX=g++-7
- conan install .
- cmake .
- make
- ctest -C Debug
- ctest -C Release
