dist: xenial
language: cpp
compiler: 
- gcc
install:
- pip install conan
- conan user
script:
- mkdir build
- cd build
- pwd
- conan install ..
- cmake ..
- ls
- cmake --build .
- cmake --build . --target test
